name: On Push (main)
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Rsync to OCF server
        run: |
          rsync
